### ISSUE TITLE
Provide CCBV for Django 1.10

### ISSUE THREAD

**Issue by ad-m** [refreshoxford/django-cbv-inspector#109]
Django 1.10 was released, so it is good to add support for them on ccbv.co.uk.

**Comment by meshy** [comment]
Quite right -- sorry it's taken so long this time. I've actually made a start in the `django-1.10` branch, but unfortunately, I have been unable to get intersphinx working in order to populate the docs links.

I'd really appreciate it if someone else could have a look -- I'm a little swamped at the moment.

**Comment by meshy** [comment]
This has now been deployed. Thanks for your patience (and to @exonian). We have another issue (#111), before it's perfect, but that's still to come.

**Comment by ad-m** [comment]
@meshy, thank you for your work.
