### ISSUE TITLE
Support 1.11?

### ISSUE THREAD

**Issue by mkoistinen** [refreshoxford/django-cbv-inspector#116]
Is this project dead? I sure hope not, its awesome!

**Comment by exonian** [comment]
It's definitely not dead, but on the other hand I think most of the limited time the main devs get around to working on it these days they're focusing on refactoring it into a static site generator rather than keeping it up to date with Django.

I do some of the latter as and when I remember and have time, but obviously forgot about it of late. I'm happy to give the 1.11 update a shot, but if you fancy having a go at it yourself then a PR would be most welcome too.

**Comment by meshy** [comment]
You're quite right, I'd simply forgotten. Sorry, been spinning a lot of plates!

**Comment by mkoistinen** [comment]
I am SO glad to hear this! I had a look at the code and its not entirely clear to me where I would start adding 1.11 support. I'm no stranger to open source projects and contributing, but I'm not seeing it. Is there a pointer to the relevant docs for that?

**Comment by exonian** [comment]
Yeah, you're right that side of things isn't documented at all! Sorry, I'd forgotten it wasn't even briefly mentioned in the readme...

But yes, that's exactly what we do, I'm afraid. I think you might also have to run `fetch_docs_urls` in between populating and exporting. Oh and you'll want to use `cbv_dumpversion` rather than Django's general dumpdata, in case you hadn't also stumbled on that one too.

Good luck! If you run into more issues than you're in the mood to clamber past, just shout and I should be able to get around to it this weekend thanks to your reminder.

**Comment by mkoistinen** [comment]
Closed by #117 / #119
