### ISSUE TITLE
Django 2.0

### ISSUE THREAD

**Issue by exonian** [refreshoxford/django-cbv-inspector#122]
So, Django 2.0's just a few months away, and with it the dropping of Python 2 support.

@ghickman and @meshy: I know you've both done work on the static pages rebuild, so I was wondering roughly what the current state of play was with that. Essentially: do you think that, with the right support from others, it could be made ready in time for us needing to support Django 2.0? I know you're both really busy so may not be able to do much or any of he dev yourselves, but I don't know the state of that rebuild well enough to determine if I could help get it over the line in time or if it's just too far out.

If it doesn't look like a dead cert to be ready in time, I'm happy to try to get the current build Python 3 ready. Of course, that'll still need hosting changes from someone with access to that but hopefully that won't be too much work.

**Comment by ghickman** [comment]
> Django 2.0's just a few months away

omg they move so fast now, that's both amazing and argh!

So, a bit of a state of the union…

The static builder is 90% done and in typical fashion the last 10% is proving the hardest.  Building the home page and nav turned out to be the hardest parts.

The concept I ran with was one of: the tool should be able to generically look at some Django and create static HTML.  To this end I've built up a system that uses virtualenvs to generate the output from each version of Django so we can "just" rely on importing Django from the current env and get some HTML at the end.

You might be seeing where the issues came in at this point… if we're generating a load of HTML _per Django version_ then how do we build a cross-version nav/get the latest version 🤦‍♂️ 

You can see [and hopefully run!] the latest work from the `static-pages-requiem` branch.  Docs on how to get set up/run it are [here](https://github.com/refreshoxford/django-cbv-inspector/tree/static-pages-requiem#installation)

> I know you're both really busy

I can't speak for @meshy but yes very much so for me :(

> do you think that, with the right support from others, it could be made ready in time for us needing to support Django 2.0?

If someone picks up the dev then I think pre-Django 2.0 is definitely doable.  I'd be more than happy to answer questions on the existing code if someone else picks up getting it past the finish line.

**Comment by exonian** [comment]
Great, I'll start digging into it one of these evenings.

Does it get views and mixins from all across Django or does it only do `views.generic` like the first version did at the point I think you started working on the rebuild?

**Comment by ghickman** [comment]
It takes a list of `sources` as part of the `generate` command, so you can pass in multiple locations where it can find CBVs like [this](https://github.com/refreshoxford/django-cbv-inspector/tree/static-pages-requiem#generate-html).

The idea with that was letting us support an arbitrary number of locations (your initial auth.mixins PR popped up when I was first building it IIRC!) with only template code needing to be changed to accommodate them.

**Comment by exonian** [comment]
Brilliant! Should have read the docs :(

**Comment by exonian** [comment]
Cool. Well I'll definitely have a go at it soon.

In the mean time, I had a quick go at making the current version python3 ready. There wasn't much to do, but it wasn't until I had finished that I realised I should probably have been going for compatibility with python2 *and* python3, so I might need to go back and get some six in there.

**Comment by meshy** [comment]
I'm not sure it's worth the extra time of making the existing codebase cross-compatible. We should already have generated the docs for the old versions, and if we need to retroactively add something, we can always check out an old version.

Thank you for looking into this, by the way @exonian `:)`

**Comment by exonian** [comment]
OK great, yeah that does make sense. That was my initial thinking and then I kinda second-guessed myself.

**Comment by ovalseven8** [comment]
For Django 2.0 we can use `super().some_method()` instead of `super(SomeClass, self).some_method()` because Django 2.0 is Python 3 only.

I think that's definitely nicer and simpler to read.

**Comment by exonian** [comment]
@ovalseven8 Yeah that syntax is way nicer! Did you mean using it in our docs or in our own classes?

If the former, I think that's already covered as Django 2.0 does use the newer syntax so when we generate fixtures from it they'll reflect that.

If the latter, @meshy has now moved `master` over to Python 3 but hasn't made this change, so it's all set ready to be done. Looks like just a couple of classes in views.py and one in models.py. If you'd like to submit a PR with the changes, that'd be really welcome!

**Comment by exonian** [comment]
Resolved by #130
